@ECHO OFF

java Main carpet.ppm 2-Colors F   dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors O   dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors J   dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors R   dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors F   dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors O   dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors J   dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors R   dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors F  dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors O  dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors J  dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors R  dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors F dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors O dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors J dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors R dith_carpet.ppm R1 D_REL1_v1 dith_carpet.r1 dith_carpet_dc.ppm

java Main carpet.ppm 2-Colors F   dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors O   dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors J   dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors R   dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors F   dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors O   dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors J   dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors R   dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors F  dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors O  dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors J  dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors R  dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors F dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors O dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors J dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors R dith_carpet.ppm R1 D_REL1_v2 dith_carpet.r1 dith_carpet_dc.ppm

java Main carpet.ppm 2-Colors F   dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors O   dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors J   dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors R   dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors F   dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors O   dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors J   dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors R   dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors F  dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors O  dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors J  dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors R  dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors F dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors O dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors J dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors R dith_carpet.ppm R2 D_REL2 dith_carpet.r2 dith_carpet_dc.ppm

java Main carpet.ppm 2-Colors F   dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors O   dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors J   dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors R   dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors F   dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors O   dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors J   dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors R   dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors F  dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors O  dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors J  dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors R  dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors F dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors O dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors J dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors R dith_carpet.ppm DXT DXT dith_carpet.dds dith_carpet_dc.ppm

java Main carpet.ppm 2-Colors F   dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors O   dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors J   dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 2-Colors R   dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors F   dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors O   dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors J   dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 8-Colors R   dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors F  dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors O  dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors J  dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 16-Colors R  dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors F dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors O dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors J dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
java Main carpet.ppm 216-Colors R dith_carpet.ppm ETC ETC dith_carpet.ktx dith_carpet_dc.ppm
