@ECHO OFF

java Main concrete.ppm 2-Colors F   dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors O   dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors J   dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors R   dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors F   dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors O   dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors J   dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors R   dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors F  dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors O  dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors J  dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors R  dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors F dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors O dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors J dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors R dith_concrete.ppm R1 D_REL1_v1 dith_concrete.r1 dith_concrete_dc.ppm

java Main concrete.ppm 2-Colors F   dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors O   dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors J   dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors R   dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors F   dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors O   dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors J   dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors R   dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors F  dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors O  dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors J  dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors R  dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors F dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors O dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors J dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors R dith_concrete.ppm R1 D_REL1_v2 dith_concrete.r1 dith_concrete_dc.ppm

java Main concrete.ppm 2-Colors F   dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors O   dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors J   dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors R   dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors F   dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors O   dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors J   dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors R   dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors F  dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors O  dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors J  dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors R  dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors F dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors O dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors J dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors R dith_concrete.ppm R2 D_REL2 dith_concrete.r2 dith_concrete_dc.ppm

java Main concrete.ppm 2-Colors F   dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors O   dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors J   dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors R   dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors F   dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors O   dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors J   dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors R   dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors F  dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors O  dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors J  dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors R  dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors F dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors O dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors J dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors R dith_concrete.ppm DXT DXT dith_concrete.dds dith_concrete_dc.ppm

java Main concrete.ppm 2-Colors F   dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors O   dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors J   dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 2-Colors R   dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors F   dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors O   dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors J   dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 8-Colors R   dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors F  dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors O  dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors J  dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 16-Colors R  dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors F dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors O dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors J dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
java Main concrete.ppm 216-Colors R dith_concrete.ppm ETC ETC dith_concrete.ktx dith_concrete_dc.ppm
