@ECHO OFF

java Main wood.ppm 2-Colors F   dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 2-Colors O   dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 2-Colors J   dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 2-Colors R   dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 8-Colors F   dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 8-Colors O   dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 8-Colors J   dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 8-Colors R   dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 16-Colors F  dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 16-Colors O  dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 16-Colors J  dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 16-Colors R  dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 216-Colors F dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 216-Colors O dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 216-Colors J dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 216-Colors R dith_wood.ppm R1 D_REL1_v1 dith_wood.r1 dith_wood_dc.ppm

java Main wood.ppm 2-Colors F   dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 2-Colors O   dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 2-Colors J   dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 2-Colors R   dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 8-Colors F   dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 8-Colors O   dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 8-Colors J   dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 8-Colors R   dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 16-Colors F  dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 16-Colors O  dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 16-Colors J  dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 16-Colors R  dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 216-Colors F dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 216-Colors O dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 216-Colors J dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm
java Main wood.ppm 216-Colors R dith_wood.ppm R1 D_REL1_v2 dith_wood.r1 dith_wood_dc.ppm

java Main wood.ppm 2-Colors F   dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 2-Colors O   dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 2-Colors J   dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 2-Colors R   dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 8-Colors F   dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 8-Colors O   dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 8-Colors J   dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 8-Colors R   dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 16-Colors F  dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 16-Colors O  dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 16-Colors J  dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 16-Colors R  dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 216-Colors F dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 216-Colors O dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 216-Colors J dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm
java Main wood.ppm 216-Colors R dith_wood.ppm R2 D_REL2 dith_wood.r2 dith_wood_dc.ppm

java Main wood.ppm 2-Colors F   dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 2-Colors O   dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 2-Colors J   dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 2-Colors R   dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 8-Colors F   dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 8-Colors O   dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 8-Colors J   dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 8-Colors R   dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 16-Colors F  dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 16-Colors O  dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 16-Colors J  dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 16-Colors R  dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 216-Colors F dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 216-Colors O dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 216-Colors J dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm
java Main wood.ppm 216-Colors R dith_wood.ppm DXT DXT dith_wood.dds dith_wood_dc.ppm

java Main wood.ppm 2-Colors F   dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 2-Colors O   dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 2-Colors J   dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 2-Colors R   dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 8-Colors F   dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 8-Colors O   dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 8-Colors J   dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 8-Colors R   dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 16-Colors F  dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 16-Colors O  dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 16-Colors J  dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 16-Colors R  dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 216-Colors F dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 216-Colors O dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 216-Colors J dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
java Main wood.ppm 216-Colors R dith_wood.ppm ETC ETC dith_wood.ktx dith_wood_dc.ppm
