call undith.bat > .\stats\undithered.txt
call baboon.bat > .\stats\stats_baboon.txt
call bamboo.bat > .\stats\stats_bamboo.txt
call carpet.bat > .\stats\stats_carpet.txt
call concrete.bat > .\stats\stats_concrete.txt
call grass.bat > .\stats\stats_grass.txt
call lena.bat > .\stats\stats_lena.txt
call pattern.bat > .\stats\stats_pattern.txt
call wood.bat > .\stats\stats_wood.txt