@ECHO OFF

java Main baboon.ppm 2-Colors F   dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors O   dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors J   dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors R   dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors F   dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors O   dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors J   dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors R   dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors F  dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors O  dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors J  dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors R  dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors F dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors O dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors J dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors R dith_baboon.ppm R1 D_REL1_v1 dith_baboon.r1 dith_baboon_dc.ppm

java Main baboon.ppm 2-Colors F   dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors O   dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors J   dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors R   dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors F   dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors O   dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors J   dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors R   dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors F  dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors O  dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors J  dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors R  dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors F dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors O dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors J dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors R dith_baboon.ppm R1 D_REL1_v2 dith_baboon.r1 dith_baboon_dc.ppm

java Main baboon.ppm 2-Colors F   dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors O   dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors J   dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors R   dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors F   dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors O   dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors J   dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors R   dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors F  dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors O  dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors J  dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors R  dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors F dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors O dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors J dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors R dith_baboon.ppm R2 D_REL2 dith_baboon.r2 dith_baboon_dc.ppm

java Main baboon.ppm 2-Colors F   dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors O   dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors J   dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors R   dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors F   dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors O   dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors J   dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors R   dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors F  dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors O  dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors J  dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors R  dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors F dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors O dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors J dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors R dith_baboon.ppm DXT DXT dith_baboon.dds dith_baboon_dc.ppm

java Main baboon.ppm 2-Colors F   dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors O   dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors J   dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 2-Colors R   dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors F   dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors O   dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors J   dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 8-Colors R   dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors F  dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors O  dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors J  dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 16-Colors R  dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors F dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors O dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors J dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm
java Main baboon.ppm 216-Colors R dith_baboon.ppm ETC ETC dith_baboon.ktx dith_baboon_dc.ppm