@ECHO OFF

java Main bamboo.ppm 2-Colors F   dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors O   dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors J   dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors R   dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors F   dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors O   dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors J   dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors R   dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors F  dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors O  dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors J  dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors R  dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors F dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors O dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors J dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors R dith_bamboo.ppm R1 D_REL1_v1 dith_bamboo.r1 dith_bamboo_dc.ppm

java Main bamboo.ppm 2-Colors F   dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors O   dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors J   dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors R   dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors F   dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors O   dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors J   dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors R   dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors F  dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors O  dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors J  dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors R  dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors F dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors O dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors J dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors R dith_bamboo.ppm R1 D_REL1_v2 dith_bamboo.r1 dith_bamboo_dc.ppm

java Main bamboo.ppm 2-Colors F   dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors O   dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors J   dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors R   dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors F   dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors O   dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors J   dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors R   dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors F  dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors O  dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors J  dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors R  dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors F dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors O dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors J dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors R dith_bamboo.ppm R2 D_REL2 dith_bamboo.r2 dith_bamboo_dc.ppm

java Main bamboo.ppm 2-Colors F   dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors O   dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors J   dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors R   dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors F   dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors O   dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors J   dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors R   dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors F  dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors O  dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors J  dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors R  dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors F dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors O dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors J dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors R dith_bamboo.ppm DXT DXT dith_bamboo.dds dith_bamboo_dc.ppm

java Main bamboo.ppm 2-Colors F   dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors O   dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors J   dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 2-Colors R   dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors F   dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors O   dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors J   dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 8-Colors R   dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors F  dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors O  dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors J  dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 16-Colors R  dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors F dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors O dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors J dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
java Main bamboo.ppm 216-Colors R dith_bamboo.ppm ETC ETC dith_bamboo.ktx dith_bamboo_dc.ppm
