@ECHO OFF

java Main grass.ppm 2-Colors F   dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 2-Colors O   dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 2-Colors J   dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 2-Colors R   dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 8-Colors F   dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 8-Colors O   dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 8-Colors J   dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 8-Colors R   dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 16-Colors F  dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 16-Colors O  dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 16-Colors J  dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 16-Colors R  dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 216-Colors F dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 216-Colors O dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 216-Colors J dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 216-Colors R dith_grass.ppm R1 D_REL1_v1 dith_grass.r1 dith_grass_dc.ppm

java Main grass.ppm 2-Colors F   dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 2-Colors O   dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 2-Colors J   dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 2-Colors R   dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 8-Colors F   dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 8-Colors O   dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 8-Colors J   dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 8-Colors R   dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 16-Colors F  dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 16-Colors O  dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 16-Colors J  dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 16-Colors R  dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 216-Colors F dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 216-Colors O dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 216-Colors J dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm
java Main grass.ppm 216-Colors R dith_grass.ppm R1 D_REL1_v2 dith_grass.r1 dith_grass_dc.ppm

java Main grass.ppm 2-Colors F   dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 2-Colors O   dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 2-Colors J   dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 2-Colors R   dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 8-Colors F   dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 8-Colors O   dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 8-Colors J   dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 8-Colors R   dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 16-Colors F  dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 16-Colors O  dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 16-Colors J  dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 16-Colors R  dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 216-Colors F dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 216-Colors O dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 216-Colors J dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm
java Main grass.ppm 216-Colors R dith_grass.ppm R2 D_REL2 dith_grass.r2 dith_grass_dc.ppm

java Main grass.ppm 2-Colors F   dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 2-Colors O   dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 2-Colors J   dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 2-Colors R   dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 8-Colors F   dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 8-Colors O   dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 8-Colors J   dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 8-Colors R   dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 16-Colors F  dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 16-Colors O  dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 16-Colors J  dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 16-Colors R  dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 216-Colors F dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 216-Colors O dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 216-Colors J dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm
java Main grass.ppm 216-Colors R dith_grass.ppm DXT DXT dith_grass.dds dith_grass_dc.ppm

java Main grass.ppm 2-Colors F   dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 2-Colors O   dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 2-Colors J   dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 2-Colors R   dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 8-Colors F   dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 8-Colors O   dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 8-Colors J   dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 8-Colors R   dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 16-Colors F  dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 16-Colors O  dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 16-Colors J  dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 16-Colors R  dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 216-Colors F dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 216-Colors O dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 216-Colors J dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
java Main grass.ppm 216-Colors R dith_grass.ppm ETC ETC dith_grass.ktx dith_grass_dc.ppm
