@ECHO OFF

java Main lena.ppm 2-Colors F   dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 2-Colors O   dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 2-Colors J   dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 2-Colors R   dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 8-Colors F   dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 8-Colors O   dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 8-Colors J   dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 8-Colors R   dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 16-Colors F  dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 16-Colors O  dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 16-Colors J  dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 16-Colors R  dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 216-Colors F dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 216-Colors O dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 216-Colors J dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 216-Colors R dith_lena.ppm R1 D_REL1_v1 dith_lena.r1 dith_lena_dc.ppm

java Main lena.ppm 2-Colors F   dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 2-Colors O   dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 2-Colors J   dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 2-Colors R   dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 8-Colors F   dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 8-Colors O   dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 8-Colors J   dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 8-Colors R   dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 16-Colors F  dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 16-Colors O  dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 16-Colors J  dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 16-Colors R  dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 216-Colors F dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 216-Colors O dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 216-Colors J dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm
java Main lena.ppm 216-Colors R dith_lena.ppm R1 D_REL1_v2 dith_lena.r1 dith_lena_dc.ppm

java Main lena.ppm 2-Colors F   dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 2-Colors O   dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 2-Colors J   dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 2-Colors R   dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 8-Colors F   dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 8-Colors O   dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 8-Colors J   dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 8-Colors R   dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 16-Colors F  dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 16-Colors O  dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 16-Colors J  dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 16-Colors R  dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 216-Colors F dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 216-Colors O dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 216-Colors J dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm
java Main lena.ppm 216-Colors R dith_lena.ppm R2 D_REL2 dith_lena.r2 dith_lena_dc.ppm

java Main lena.ppm 2-Colors F   dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 2-Colors O   dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 2-Colors J   dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 2-Colors R   dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 8-Colors F   dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 8-Colors O   dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 8-Colors J   dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 8-Colors R   dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 16-Colors F  dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 16-Colors O  dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 16-Colors J  dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 16-Colors R  dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 216-Colors F dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 216-Colors O dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 216-Colors J dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm
java Main lena.ppm 216-Colors R dith_lena.ppm DXT DXT dith_lena.dds dith_lena_dc.ppm

java Main lena.ppm 2-Colors F   dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 2-Colors O   dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 2-Colors J   dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 2-Colors R   dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 8-Colors F   dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 8-Colors O   dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 8-Colors J   dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 8-Colors R   dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 16-Colors F  dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 16-Colors O  dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 16-Colors J  dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 16-Colors R  dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 216-Colors F dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 216-Colors O dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 216-Colors J dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
java Main lena.ppm 216-Colors R dith_lena.ppm ETC ETC dith_lena.ktx dith_lena_dc.ppm
