@ECHO OFF

java Main pattern.ppm 2-Colors F   dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors O   dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors J   dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors R   dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors F   dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors O   dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors J   dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors R   dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors F  dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors O  dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors J  dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors R  dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors F dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors O dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors J dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors R dith_pattern.ppm R1 D_REL1_v1 dith_pattern.r1 dith_pattern_dc.ppm

java Main pattern.ppm 2-Colors F   dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors O   dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors J   dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors R   dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors F   dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors O   dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors J   dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors R   dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors F  dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors O  dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors J  dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors R  dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors F dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors O dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors J dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors R dith_pattern.ppm R1 D_REL1_v2 dith_pattern.r1 dith_pattern_dc.ppm

java Main pattern.ppm 2-Colors F   dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors O   dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors J   dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors R   dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors F   dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors O   dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors J   dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors R   dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors F  dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors O  dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors J  dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors R  dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors F dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors O dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors J dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors R dith_pattern.ppm R2 D_REL2 dith_pattern.r2 dith_pattern_dc.ppm

java Main pattern.ppm 2-Colors F   dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors O   dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors J   dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors R   dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors F   dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors O   dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors J   dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors R   dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors F  dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors O  dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors J  dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors R  dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors F dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors O dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors J dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors R dith_pattern.ppm DXT DXT dith_pattern.dds dith_pattern_dc.ppm

java Main pattern.ppm 2-Colors F   dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors O   dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors J   dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 2-Colors R   dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors F   dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors O   dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors J   dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 8-Colors R   dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors F  dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors O  dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors J  dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 16-Colors R  dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors F dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors O dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors J dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
java Main pattern.ppm 216-Colors R dith_pattern.ppm ETC ETC dith_pattern.ktx dith_pattern_dc.ppm
